import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import RecognizedSection from "@/components/RecognizedSection";
import BackToTop from "@/components/BackToTop";
import CopyProtection from "@/components/CopyProtection";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  verification: {
    google: "sFKoMvqE4YbTOi32q1bNbL_3TvmZh-Bb_mRqocziB9Y",
    other: {
      "msvalidate.01": "859B1652FEA3BFC46564A0CB3B223931",
    },
  },
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-1MD1QWENDM"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-1MD1QWENDM');`}
        </Script>
        {/* <CopyProtection /> */}
        <Header />
        {children}
        <RecognizedSection />
        <Footer />
        <BackToTop />
      </body>
    </html>
  );
}
